import { BleError, BleManager, Device, State as BluetoothState, type DeviceId, type TransactionId, type UUID, type Characteristic, type Base64, type Subscription } from 'react-native-ble-plx';
declare class BLEServiceInstance {
    manager: BleManager;
    device: Device | null;
    characteristicMonitor: Subscription | null;
    isCharacteristicMonitorDisconnectExpected: boolean;
    constructor();
    createNewManager: () => void;
    getDevice: () => Device | null;
    initializeBLE: () => Promise<void>;
    disconnectDevice: () => Promise<void>;
    disconnectDeviceById: (id: DeviceId) => Promise<void>;
    onBluetoothPowerOff: () => void;
    scanDevices: (onDeviceFound: (device: Device) => void, UUIDs?: UUID[] | null, legacyScan?: boolean) => Promise<void>;
    connectToDevice: (deviceId: DeviceId) => Promise<Device>;
    discoverAllServicesAndCharacteristicsForDevice: () => Promise<Device>;
    readCharacteristicForDevice: (serviceUUID: UUID, characteristicUUID: UUID) => Promise<Characteristic>;
    writeCharacteristicWithResponseForDevice: (serviceUUID: UUID, characteristicUUID: UUID, time: Base64) => Promise<void | Characteristic>;
    writeCharacteristicWithoutResponseForDevice: (serviceUUID: UUID, characteristicUUID: UUID, time: Base64) => Promise<void | Characteristic>;
    setupMonitor: (serviceUUID: UUID, characteristicUUID: UUID, onCharacteristicReceived: (characteristic: Characteristic) => void, onError: (error: Error) => void, transactionId?: TransactionId, hideErrorDisplay?: boolean) => void;
    setupCustomMonitor: BleManager['monitorCharacteristicForDevice'];
    finishMonitor: () => void;
    writeDescriptorForDevice: (serviceUUID: UUID, characteristicUUID: UUID, descriptorUUID: UUID, data: Base64) => Promise<void | import("react-native-ble-plx").Descriptor>;
    readDescriptorForDevice: (serviceUUID: UUID, characteristicUUID: UUID, descriptorUUID: UUID) => Promise<void | import("react-native-ble-plx").Descriptor>;
    getServicesForDevice: () => Promise<void | import("react-native-ble-plx").Service[]>;
    getCharacteristicsForDevice: (serviceUUID: UUID) => Promise<void | Characteristic[]>;
    getDescriptorsForDevice: (serviceUUID: UUID, characteristicUUID: UUID) => Promise<void | import("react-native-ble-plx").Descriptor[]>;
    isDeviceConnected: () => Promise<boolean>;
    isDeviceWithIdConnected: (id: DeviceId) => Promise<boolean | void>;
    getConnectedDevices: (expectedServices: UUID[]) => Promise<void | Device[]>;
    requestMTUForDevice: (mtu: number) => Promise<void | Device>;
    onDeviceDisconnected: (listener: (error: BleError | null, device: Device | null) => void) => Subscription;
    onDeviceDisconnectedCustom: BleManager['onDeviceDisconnected'];
    readRSSIForDevice: () => Promise<void | Device>;
    getDevices: () => Promise<void | Device[]>;
    cancelTransaction: (transactionId: TransactionId) => Promise<void>;
    enable: () => Promise<void | BleManager>;
    disable: () => Promise<void | BleManager>;
    getState: () => Promise<void | BluetoothState>;
    onError: (error: BleError) => void;
    requestConnectionPriorityForDevice: (priority: 0 | 1 | 2) => Promise<Device>;
    cancelDeviceConnection: () => Promise<Device>;
    requestBluetoothPermission: () => Promise<boolean>;
    showErrorToast: (error: string) => void;
    showSuccessToast: (info: string) => void;
}
export declare const BLEService: BLEServiceInstance;
export {};
//# sourceMappingURL=BLEService.d.ts.map